services:
  traefik:
    image: traefik:v3.3.0-rc1
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  web:
    image: kang-tech-vault-web:0.0.1
    depends_on:
      - api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`kang-vault.com`)"
      - "traefik.http.services.web.loadbalancer.server.port=80"
  api:
    image: kang-tech-vault-api:0.0.1
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${DATABASE_NAME}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      LOGIN_TOKEN_EXPIRATION_TIME_MILLIS: ${LOGIN_TOKEN_EXPIRATION_TIME_MILLIS}
      REGISTER_EMAIL_VERIFY_BASEURL: ${REGISTER_EMAIL_VERIFY_BASEURL}
      REGISTER_TOKEN_TIME: ${REGISTER_TOKEN_TIME}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.api.loadbalancer.server.port=80"
      - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.api.rule=Host(`kang-vault.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.middlewares=api-stripprefix"
  db:
    image: mysql:8.4.2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  db-data:
