version: '3.7'

services:
  # web:
  #   image: kang-tech-vault-web:0.0.1
  #   depends_on:
  #     - api
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  api:
    image: kang-tech-vault-api:0.0.1
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${DATABASE_NAME}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
  db:
    image: mysql:8.4.2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  db-data: