auth:
  expiration:
    time-millis: 86400000 # 1000 * 60 * 60 * 24
spring:
  application:
    name: Demonstration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: none